#!/bin/bash

set -xeuo pipefail

rel_sos_path="ci-framework-data/logs/openstack-k8s-operators-openstack-must-gather/sos-reports/_all_nodes/"
rel_tempest_log_path="ci-framework-data/tests/test_operator/tempest-tests/tempest.log"

log_base="$1"

wget -e robots=off -A '*.tar.xz' --no-parent --recursive --level=1 --no-directories "$log_base$rel_sos_path"

for f in *compute-*.tar.xz ; do
    tar ixf "$f" || true
    rm "$f"
done

for f in *ceph-*.tar.xz ; do
    tar ixf "$f" || true
    rm "$f" || true
done


mkdir podlogs
for f in *.tar.xz ; do
    dir=${f%"-UntarWithArg-i.tar.xz"}
    mkdir "$dir"
    tar ixf "$f" -C "$dir" || true
    rm "$f"
    poddir=${dir#"sosreport-"}
    mkdir "podlogs/$poddir"
    mv "$dir/podlogs/var/log/pods" "podlogs/$poddir/" || true
done

wget "$log_base$rel_tempest_log_path" || true

ln -s $(eval "ls podlogs/*/pods/*/tempest-tests-tests-runner/0.log") tempest-pod.log || true

